receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  attributes:
    actions:
      - key: service.name
        value: rispo
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: rispo
    const_labels:
      environment: production
  
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlp/tempo]
    
    metrics:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [prometheus]
